# Generated by Django 3.1.6 on 2021-05-04 23:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mymaintenance_app', '0005_profile_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=300)),
                ('work_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mymaintenance_app.workorder')),
            ],
        ),
    ]
